import type { Todo } from "./todo-types"

export const mockTodos: Todo[] = [
  // =============================================
  //  OPEN TODOS (sorted by priorityScore desc)
  // =============================================

  // --- PAYMENTS ---
  {
    id: "todo-1",
    title: "Update Payment Method",
    description:
      "Your credit card on file has expired. Please update your payment method to avoid any disruption to your active campaigns.",
    archetype: "payment",
    status: "not_started",
    priority: "critical",
    priorityScore: 0.95,
    blocking: true,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-02-08T00:00:00Z",
    requestedDate: "2026-02-04T10:00:00Z",
    productName: "Account Billing",
    fields: [
      {
        id: "card_number",
        label: "Card Number",
        type: "text",
        placeholder: "1234 5678 9012 3456",
        helpText: "Enter your 16-digit card number",
        required: true,
      },
      {
        id: "expiry",
        label: "Expiry Date",
        type: "text",
        placeholder: "MM/YY",
        helpText: "Enter the expiration date on your card",
        required: true,
      },
      {
        id: "cvv",
        label: "CVV",
        type: "text",
        placeholder: "123",
        helpText: "3-digit security code on the back of your card",
        required: true,
      },
    ],
  },

  // --- INTEGRATIONS ---
  {
    id: "todo-2",
    title: "Connect Google Business Profile",
    description:
      "Connect your Google Business Profile so we can manage your local listing, respond to reviews, and track local search performance.",
    archetype: "integration",
    status: "not_started",
    priority: "high",
    priorityScore: 0.88,
    blocking: true,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-02-10T00:00:00Z",
    requestedDate: "2026-02-03T14:30:00Z",
    productName: "Local SEO",
    integrationFlow: "google_business_profile",
  },

  // --- INFORMATION REQUESTS ---
  {
    id: "todo-3",
    title: "Upload Business Logo",
    description:
      "Upload a high-resolution version of your business logo. This will be used across your website, social media profiles, and marketing materials.",
    archetype: "information_request",
    status: "in_progress",
    priority: "high",
    priorityScore: 0.78,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-02-12T00:00:00Z",
    requestedDate: "2026-02-02T09:00:00Z",
    productName: "Website Design",
    fields: [
      {
        id: "logo_file",
        label: "Logo File",
        type: "file",
        helpText:
          "Upload PNG, SVG, or AI format. Minimum 500x500px recommended.",
        required: true,
      },
      {
        id: "logo_guidelines",
        label: "Brand Guidelines (Optional)",
        type: "file",
        helpText: "Upload any brand guidelines document if available",
        required: false,
      },
    ],
  },

  // --- FEEDBACK REQUESTS ---
  {
    id: "todo-4",
    title: "Approve Website Draft",
    description:
      "Your website draft is ready for review. Please review all pages and approve or request changes.",
    archetype: "feedback_request",
    status: "not_started",
    priority: "high",
    priorityScore: 0.76,
    blocking: true,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 15,
    dueDate: "2026-02-11T00:00:00Z",
    requestedDate: "2026-02-05T11:00:00Z",
    productName: "Website Design",
    vendorMessage:
      "Hi! We have completed the initial draft of your website. Please review the homepage, about page, and service pages. Let us know if you'd like any changes to the layout, colors, or content.",
    vendorFiles: ["website-draft-preview.pdf"],
  },
  {
    id: "todo-4b",
    title: "Approve PR Article Draft",
    description:
      "A draft PR article has been prepared for your review. Please approve the content or suggest edits before publication.",
    archetype: "feedback_request",
    status: "not_started",
    priority: "high",
    priorityScore: 0.73,
    blocking: true,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 10,
    dueDate: "2026-02-13T00:00:00Z",
    requestedDate: "2026-02-06T09:00:00Z",
    productName: "PR & Content",
    vendorMessage:
      "We've drafted a press release highlighting your latest service expansion. Please review the article for accuracy and tone, and let us know if any changes are needed.",
    vendorFiles: ["pr-article-draft-v1.docx"],
  },
  {
    id: "todo-4c",
    title: "Approve Campaign Brief",
    description:
      "Your PPC campaign brief is ready for review. Please confirm targeting, budget, and ad copy direction before we launch.",
    archetype: "feedback_request",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.64,
    blocking: true,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 10,
    dueDate: "2026-02-14T00:00:00Z",
    requestedDate: "2026-02-06T14:00:00Z",
    productName: "PPC Management",
    vendorMessage:
      "Here is the campaign brief for your Google Ads campaign. It includes target keywords, audience segments, daily budget recommendation, and sample ad copy. Please review and confirm so we can proceed with setup.",
    vendorFiles: ["campaign-brief.pdf"],
  },

  // --- INFORMATION REQUESTS (continued) ---
  {
    id: "todo-5",
    title: "Provide Hosting Credentials",
    description:
      "We need access to your current hosting provider to migrate your website. Please provide your hosting login credentials securely.",
    archetype: "information_request",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.62,
    blocking: true,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-02-14T00:00:00Z",
    requestedDate: "2026-02-04T08:00:00Z",
    productName: "Website Migration",
    fields: [
      {
        id: "host_provider",
        label: "Hosting Provider",
        type: "text",
        placeholder: "e.g., GoDaddy, Bluehost, SiteGround",
        helpText: "Name of your current hosting provider",
        required: true,
      },
      {
        id: "host_username",
        label: "Username / Email",
        type: "email",
        placeholder: "your-email@example.com",
        required: true,
      },
      {
        id: "host_password",
        label: "Password",
        type: "credentials",
        helpText:
          "Your credentials are encrypted and stored securely. They will only be used for migration.",
        required: true,
      },
    ],
  },

  // --- INTEGRATIONS (continued) ---
  {
    id: "todo-6",
    title: "Connect Google Ads Account",
    description:
      "Connect your Google Ads account to enable campaign management and performance tracking.",
    archetype: "integration",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.58,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-02-15T00:00:00Z",
    requestedDate: "2026-02-03T16:00:00Z",
    productName: "PPC Management",
    integrationFlow: "google_ads",
  },
  {
    id: "todo-6b",
    title: "Connect Facebook Ads",
    description:
      "Connect your Facebook Ads account so we can manage and optimize your social media advertising campaigns.",
    archetype: "integration",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.55,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-02-16T00:00:00Z",
    requestedDate: "2026-02-03T16:30:00Z",
    productName: "Social Media Ads",
    fields: [
      {
        id: "fb_ad_account_id",
        label: "Facebook Ad Account ID",
        type: "text",
        placeholder: "e.g., act_123456789",
        helpText: "You can find this in your Facebook Business Manager under Ad Accounts.",
        required: true,
      },
    ],
  },
  {
    id: "todo-6c",
    title: "Provide DNS Access for Domain Configuration",
    description:
      "Provide access to your domain's DNS settings so we can configure your domain for website hosting and email routing.",
    archetype: "integration",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.52,
    blocking: true,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-02-15T00:00:00Z",
    requestedDate: "2026-02-04T11:00:00Z",
    productName: "Website",
    fields: [
      {
        id: "domain_registrar",
        label: "Domain Registrar",
        type: "text",
        placeholder: "e.g., GoDaddy, Namecheap, Google Domains",
        helpText: "Where did you purchase your domain?",
        required: true,
      },
      {
        id: "dns_username",
        label: "Login Email / Username",
        type: "email",
        placeholder: "your-email@example.com",
        required: true,
      },
      {
        id: "dns_password",
        label: "Password",
        type: "credentials",
        helpText: "Credentials are encrypted and used only for DNS configuration.",
        required: true,
      },
    ],
  },
  {
    id: "todo-6d",
    title: "Verify Domain Ownership",
    description:
      "Verify that you own your domain by adding a TXT record to your DNS settings. This is required before we can proceed with website setup.",
    archetype: "integration",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.50,
    blocking: true,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-02-16T00:00:00Z",
    requestedDate: "2026-02-04T12:00:00Z",
    productName: "Website",
    fields: [
      {
        id: "domain_name",
        label: "Domain Name",
        type: "text",
        placeholder: "e.g., yourbusiness.com",
        helpText: "Enter your primary domain name",
        required: true,
      },
    ],
  },

  // --- INFORMATION REQUESTS (continued) ---
  {
    id: "todo-7",
    title: "Provide SEO Keywords",
    description:
      "Share the keywords you'd like to target for your SEO campaign. If you're unsure, we'll suggest keywords based on your industry and location.",
    archetype: "information_request",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.48,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-02-16T00:00:00Z",
    requestedDate: "2026-02-03T09:00:00Z",
    productName: "Local SEO",
    fields: [
      {
        id: "keywords",
        label: "Target Keywords",
        type: "textarea",
        placeholder:
          "e.g., plumber near me, emergency plumbing, drain cleaning",
        helpText:
          "Enter keywords separated by commas. We recommend 5-10 primary keywords.",
        required: true,
      },
      {
        id: "location",
        label: "Target Location",
        type: "text",
        placeholder: "e.g., San Francisco, CA",
        helpText: "Primary service area for your SEO campaign",
        required: true,
      },
    ],
  },
  {
    id: "todo-7b",
    title: "Provide Website Login Credentials",
    description:
      "We need admin access to your current website to perform technical SEO changes and content updates.",
    archetype: "information_request",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.46,
    blocking: true,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 3,
    dueDate: "2026-02-14T00:00:00Z",
    requestedDate: "2026-02-04T09:30:00Z",
    productName: "Website Design",
    fields: [
      {
        id: "cms_url",
        label: "Website Admin URL",
        type: "url",
        placeholder: "e.g., https://yourbusiness.com/wp-admin",
        helpText: "The URL you use to log in to your website's admin panel",
        required: true,
      },
      {
        id: "cms_username",
        label: "Username / Email",
        type: "text",
        placeholder: "admin or your-email@example.com",
        required: true,
      },
      {
        id: "cms_password",
        label: "Password",
        type: "credentials",
        helpText: "Your credentials are encrypted and stored securely.",
        required: true,
      },
    ],
  },
  {
    id: "todo-7c",
    title: "Upload Required Documents",
    description:
      "Please upload your business license, insurance certificate, and any other required documents for your marketing campaigns.",
    archetype: "information_request",
    status: "not_started",
    priority: "low",
    priorityScore: 0.42,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-02-18T00:00:00Z",
    requestedDate: "2026-02-04T10:00:00Z",
    productName: "Account Setup",
    fields: [
      {
        id: "business_license",
        label: "Business License",
        type: "file",
        helpText: "Upload a copy of your valid business license (PDF or image)",
        required: true,
      },
      {
        id: "insurance_cert",
        label: "Insurance Certificate",
        type: "file",
        helpText: "Upload your certificate of insurance",
        required: true,
      },
      {
        id: "additional_docs",
        label: "Additional Documents (Optional)",
        type: "file",
        helpText: "Upload any other relevant documents (photos, certifications, etc.)",
        required: false,
      },
    ],
  },
  {
    id: "todo-7d",
    title: "Submit Review Replies",
    description:
      "Draft and submit replies for recent customer reviews on Google and Yelp. Responding promptly improves your online reputation.",
    archetype: "information_request",
    status: "not_started",
    priority: "low",
    priorityScore: 0.38,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 15,
    dueDate: "2026-02-20T00:00:00Z",
    requestedDate: "2026-02-05T08:00:00Z",
    productName: "Reputation Management",
    fields: [
      {
        id: "review_replies",
        label: "Review Replies",
        type: "textarea",
        placeholder: "Draft your replies to recent reviews...",
        helpText: "You can provide replies for multiple reviews. We'll match them to the right review.",
        required: true,
      },
    ],
  },

  // --- VENDOR REQUESTS ---
  {
    id: "todo-10",
    title: "Provide Additional Information Requested by Vendor",
    description:
      "The vendor working on your website has requested additional details about your services and service areas to complete the content.",
    archetype: "vendor_request",
    status: "not_started",
    priority: "high",
    priorityScore: 0.72,
    blocking: true,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 10,
    dueDate: "2026-02-12T00:00:00Z",
    requestedDate: "2026-02-06T10:00:00Z",
    productName: "Website Design",
    vendorMessage:
      "Hi! We need a few more details to finalize the service pages: 1) Please list all services you offer with a brief description for each. 2) What areas/cities do you serve? 3) Do you have any customer testimonials we can feature?",
    fields: [
      {
        id: "services_list",
        label: "Services Offered",
        type: "textarea",
        placeholder: "e.g., Residential Plumbing, Commercial Plumbing, Drain Cleaning...",
        helpText: "List each service with a brief description",
        required: true,
      },
      {
        id: "service_areas",
        label: "Service Areas",
        type: "textarea",
        placeholder: "e.g., San Francisco, Oakland, Berkeley...",
        helpText: "List the cities or neighborhoods you serve",
        required: true,
      },
      {
        id: "testimonials",
        label: "Customer Testimonials (Optional)",
        type: "textarea",
        placeholder: "Paste any customer testimonials you'd like featured...",
        required: false,
      },
    ],
  },
  {
    id: "todo-10b",
    title: "Website Draft Ready for Review",
    description:
      "Your website design draft has been submitted by the vendor and is ready for your review.",
    archetype: "vendor_request",
    status: "not_started",
    priority: "high",
    priorityScore: 0.70,
    blocking: true,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 20,
    dueDate: "2026-02-13T00:00:00Z",
    requestedDate: "2026-02-07T11:00:00Z",
    productName: "Website Design",
    vendorMessage:
      "The website design is complete and ready for your review. Please check the homepage layout, service pages, contact form, and mobile responsiveness. Let us know your feedback.",
    vendorFiles: ["website-design-preview-v2.pdf", "mobile-mockups.pdf"],
  },
  {
    id: "todo-10c",
    title: "Ads Campaign Created - Approval Required",
    description:
      "Your Google Ads campaign has been set up and is awaiting your final approval before going live.",
    archetype: "vendor_request",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.60,
    blocking: true,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 10,
    dueDate: "2026-02-15T00:00:00Z",
    requestedDate: "2026-02-08T09:00:00Z",
    productName: "PPC Management",
    vendorMessage:
      "Your Google Ads campaign is ready! Here's a summary:\n- 3 ad groups targeting your primary services\n- 25 keywords selected\n- Daily budget: $50\n- Estimated impressions: 1,500-2,000/day\n\nPlease review and approve to launch.",
    vendorFiles: ["campaign-setup-summary.pdf"],
  },
  {
    id: "todo-10d",
    title: "SSL Activation Pending",
    description:
      "SSL certificate activation is pending for your domain. Please confirm domain ownership to proceed with HTTPS activation.",
    archetype: "vendor_request",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.56,
    blocking: false,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 5,
    dueDate: "2026-02-16T00:00:00Z",
    requestedDate: "2026-02-07T14:00:00Z",
    productName: "Website",
    vendorMessage:
      "We need to activate the SSL certificate for your domain. Please confirm that you own the domain and have access to the admin email associated with it.",
  },

  // --- PAYMENTS (continued) ---
  {
    id: "todo-11",
    title: "Pay / Approve Invoice",
    description:
      "A new invoice is ready for your review and payment. Please approve and process the payment to keep your campaigns running.",
    archetype: "payment",
    status: "not_started",
    priority: "high",
    priorityScore: 0.80,
    blocking: true,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-02-09T00:00:00Z",
    requestedDate: "2026-02-05T08:00:00Z",
    productName: "Account Billing",
  },
  {
    id: "todo-11b",
    title: "Subscription Payment Failed",
    description:
      "Your most recent subscription payment has failed. Please update your payment method or retry the payment to avoid service interruption.",
    archetype: "payment",
    status: "not_started",
    priority: "critical",
    priorityScore: 0.93,
    blocking: true,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-02-07T00:00:00Z",
    requestedDate: "2026-02-04T12:00:00Z",
    productName: "Account Billing",
  },
  {
    id: "todo-11c",
    title: "Credit Card Expiring Soon",
    description:
      "Your payment card ending in 4242 expires next month. Update your card to prevent payment failures on your active subscriptions.",
    archetype: "payment",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.45,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-03-01T00:00:00Z",
    requestedDate: "2026-02-05T10:00:00Z",
    productName: "Account Billing",
  },
  {
    id: "todo-11d",
    title: "Add Payment Method",
    description:
      "Please add a payment method to your account to proceed with plan activation.",
    archetype: "payment",
    status: "not_started",
    priority: "high",
    priorityScore: 0.82,
    blocking: true,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-02-08T00:00:00Z",
    requestedDate: "2026-02-03T08:00:00Z",
    productName: "Account Billing",
    fields: [
      {
        id: "card_number",
        label: "Card Number",
        type: "text",
        placeholder: "1234 5678 9012 3456",
        required: true,
      },
      {
        id: "expiry",
        label: "Expiry Date",
        type: "text",
        placeholder: "MM/YY",
        required: true,
      },
      {
        id: "cvv",
        label: "CVV",
        type: "text",
        placeholder: "123",
        required: true,
      },
      {
        id: "cardholder_name",
        label: "Cardholder Name",
        type: "text",
        placeholder: "John Doe",
        required: true,
      },
    ],
  },

  // --- SYSTEM ALERTS ---
  {
    id: "todo-8",
    title: "DNS Misconfiguration Detected",
    description:
      "We detected a DNS misconfiguration on your domain. This may affect your website performance and email delivery. Please review and fix the issue.",
    archetype: "system_alert",
    status: "not_started",
    priority: "high",
    priorityScore: 0.68,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 10,
    dueDate: null,
    requestedDate: "2026-02-05T07:00:00Z",
    productName: "Website",
  },
  {
    id: "todo-8b",
    title: "OAuth Token Expired",
    description:
      "Your Google Ads OAuth token has expired. Please re-authorize so we can continue managing your campaigns.",
    archetype: "system_alert",
    status: "not_started",
    priority: "high",
    priorityScore: 0.66,
    blocking: true,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: null,
    requestedDate: "2026-02-06T06:00:00Z",
    productName: "PPC Management",
  },
  {
    id: "todo-8c",
    title: "Tracking Pixel Not Firing",
    description:
      "The tracking pixel on your website is not firing correctly. This affects conversion tracking for your ads campaigns.",
    archetype: "system_alert",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.54,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 10,
    dueDate: null,
    requestedDate: "2026-02-06T08:00:00Z",
    productName: "PPC Management",
  },
  {
    id: "todo-8d",
    title: "Google Ads Disapproved Ads",
    description:
      "Some of your Google Ads have been disapproved by Google. Please review the flagged ads and update them to comply with Google's policies.",
    archetype: "system_alert",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.50,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 15,
    dueDate: null,
    requestedDate: "2026-02-07T07:00:00Z",
    productName: "PPC Management",
  },

  // --- INFORMATION REQUESTS (low priority) ---
  {
    id: "todo-9",
    title: "Select Business Category",
    description:
      "Choose the most appropriate business category. This helps search engines understand your business and show it in relevant results.",
    archetype: "information_request",
    status: "not_started",
    priority: "low",
    priorityScore: 0.30,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 3,
    dueDate: "2026-02-20T00:00:00Z",
    requestedDate: "2026-02-03T10:00:00Z",
    productName: "Local SEO",
    fields: [
      {
        id: "category",
        label: "Business Category",
        type: "dropdown",
        helpText:
          "Select the primary category that best describes your business",
        required: true,
        options: [
          "Plumbing",
          "Electrical",
          "HVAC",
          "Roofing",
          "General Contractor",
          "Landscaping",
          "Cleaning Service",
          "Auto Repair",
          "Dental",
          "Medical Practice",
          "Law Firm",
          "Restaurant",
          "Other",
        ],
      },
    ],
  },
  {
    id: "todo-9b",
    title: "Provide PPC Keywords",
    description:
      "Provide the keywords you'd like to bid on for your PPC campaigns. These will be used to target potential customers searching for your services.",
    archetype: "information_request",
    status: "not_started",
    priority: "low",
    priorityScore: 0.28,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-02-20T00:00:00Z",
    requestedDate: "2026-02-04T10:30:00Z",
    productName: "PPC Management",
    fields: [
      {
        id: "ppc_keywords",
        label: "PPC Target Keywords",
        type: "textarea",
        placeholder: "e.g., emergency plumber, water heater repair, pipe leak fix",
        helpText: "Enter keywords separated by commas. Include location-specific terms for better targeting.",
        required: true,
      },
    ],
  },

  // =============================================
  //  COMPLETED TODOS (one per open todo)
  // =============================================

  // --- C1: Corresponds to todo-1 (Update Payment Method) ---
  {
    id: "todo-c1",
    title: "Update Payment Method",
    description:
      "Credit card on file was updated successfully to keep campaigns running without disruption.",
    archetype: "payment",
    status: "completed",
    priority: "critical",
    priorityScore: 0.95,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-01-20T00:00:00Z",
    requestedDate: "2026-01-17T10:00:00Z",
    completedDate: "2026-01-18T09:30:00Z",
    productName: "Account Billing",
    completedData: {
      "Card Type": "Visa",
      "Card Ending": "4242",
      "Expiry": "09/28",
      "Cardholder": "John Doe",
    },
  },

  // --- C2: Corresponds to todo-2 (Connect Google Business Profile) ---
  {
    id: "todo-c2",
    title: "Connect Google Business Profile",
    description:
      "Google Business Profile connected for local listing management and review tracking.",
    archetype: "integration",
    status: "completed",
    priority: "high",
    priorityScore: 0.88,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-01-22T00:00:00Z",
    requestedDate: "2026-01-18T14:30:00Z",
    completedDate: "2026-01-19T11:15:00Z",
    productName: "Local SEO",
    completedData: {
      "Account": "john@bayareaplumbingpros.com",
      "Business Name": "Bay Area Plumbing Pros",
      "Listing Status": "Verified",
      "Connected Via": "Google OAuth",
    },
  },

  // --- C3: Corresponds to todo-3 (Upload Business Logo) ---
  {
    id: "todo-c3",
    title: "Upload Business Logo",
    description:
      "High-resolution business logo uploaded for website, social media, and marketing materials.",
    archetype: "information_request",
    status: "completed",
    priority: "high",
    priorityScore: 0.78,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-01-25T00:00:00Z",
    requestedDate: "2026-01-20T09:00:00Z",
    completedDate: "2026-01-21T14:22:00Z",
    productName: "Website Design",
    completedData: {
      "Logo File": "bapp-logo-final.svg",
      "Format": "SVG (vector), PNG (1200x1200px)",
      "Brand Guidelines": "brand-guidelines-v2.pdf",
    },
  },

  // --- C4: Corresponds to todo-4 (Approve Website Draft) ---
  {
    id: "todo-c4",
    title: "Approve Website Draft",
    description:
      "Website draft reviewed and approved. Vendor proceeding with final build.",
    archetype: "feedback_request",
    status: "completed",
    priority: "high",
    priorityScore: 0.76,
    blocking: false,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 15,
    dueDate: "2026-01-24T00:00:00Z",
    requestedDate: "2026-01-20T11:00:00Z",
    completedDate: "2026-01-22T16:45:00Z",
    productName: "Website Design",
    vendorMessage:
      "Hi! We have completed the initial draft of your website. Please review the homepage, about page, and service pages.",
    vendorFiles: ["website-draft-preview.pdf"],
    completedData: {
      "Decision": "Approved",
      "Feedback": "Homepage looks great. Minor tweak on About page copy requested.",
      "Pages Reviewed": "Homepage, About, Services, Contact",
    },
  },

  // --- C5: Corresponds to todo-4b (Approve PR Article Draft) ---
  {
    id: "todo-c5",
    title: "Approve PR Article Draft",
    description:
      "PR article draft reviewed and approved for publication.",
    archetype: "feedback_request",
    status: "completed",
    priority: "high",
    priorityScore: 0.73,
    blocking: false,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 10,
    dueDate: "2026-01-26T00:00:00Z",
    requestedDate: "2026-01-22T09:00:00Z",
    completedDate: "2026-01-24T10:30:00Z",
    productName: "PR & Content",
    vendorMessage:
      "We've drafted a press release highlighting your latest service expansion. Please review for accuracy.",
    vendorFiles: ["pr-article-draft-v1.docx"],
    completedData: {
      "Decision": "Approved with minor edits",
      "Feedback": "Change the quote in paragraph 3 to reflect our new tagline.",
      "Article Title": "Bay Area Plumbing Pros Expands Emergency Services",
    },
  },

  // --- C6: Corresponds to todo-4c (Approve Campaign Brief) ---
  {
    id: "todo-c6",
    title: "Approve Campaign Brief",
    description:
      "PPC campaign brief confirmed. Campaign setup proceeding.",
    archetype: "feedback_request",
    status: "completed",
    priority: "medium",
    priorityScore: 0.64,
    blocking: false,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 10,
    dueDate: "2026-01-27T00:00:00Z",
    requestedDate: "2026-01-22T14:00:00Z",
    completedDate: "2026-01-25T09:00:00Z",
    productName: "PPC Management",
    vendorMessage:
      "Here is the campaign brief for your Google Ads campaign including keywords, budget, and ad copy.",
    vendorFiles: ["campaign-brief.pdf"],
    completedData: {
      "Decision": "Approved",
      "Confirmed Budget": "$50/day",
      "Target Keywords": "25 keywords approved",
      "Launch Date": "Jan 28, 2026",
    },
  },

  // --- C7: Corresponds to todo-5 (Provide Hosting Credentials) ---
  {
    id: "todo-c7",
    title: "Provide Hosting Credentials",
    description:
      "Hosting credentials submitted securely. Migration team has access.",
    archetype: "information_request",
    status: "completed",
    priority: "medium",
    priorityScore: 0.62,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-01-27T00:00:00Z",
    requestedDate: "2026-01-20T08:00:00Z",
    completedDate: "2026-01-21T10:15:00Z",
    productName: "Website Migration",
    completedData: {
      "Hosting Provider": "GoDaddy",
      "Username": "john@bayareaplumbingpros.com",
      "Password": "********** (encrypted)",
      "Status": "Credentials verified",
    },
  },

  // --- C8: Corresponds to todo-6 (Connect Google Ads Account) ---
  {
    id: "todo-c8",
    title: "Connect Google Ads Account",
    description:
      "Google Ads account connected for campaign management and tracking.",
    archetype: "integration",
    status: "completed",
    priority: "medium",
    priorityScore: 0.58,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-01-28T00:00:00Z",
    requestedDate: "2026-01-20T16:00:00Z",
    completedDate: "2026-01-22T14:00:00Z",
    productName: "PPC Management",
    completedData: {
      "Account": "Bay Area Plumbing Pros",
      "Customer ID": "123-456-7890",
      "Connected Email": "john@bayareaplumbingpros.com",
      "Status": "Connected and active",
    },
  },

  // --- C9: Corresponds to todo-6b (Connect Facebook Ads) ---
  {
    id: "todo-c9",
    title: "Connect Facebook Ads",
    description:
      "Facebook Ads account connected for social media campaign management.",
    archetype: "integration",
    status: "completed",
    priority: "medium",
    priorityScore: 0.55,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-01-29T00:00:00Z",
    requestedDate: "2026-01-20T16:30:00Z",
    completedDate: "2026-01-23T09:45:00Z",
    productName: "Social Media Ads",
    completedData: {
      "Ad Account ID": "act_987654321",
      "Connected Page": "Bay Area Plumbing Pros",
      "Status": "Connected",
    },
  },

  // --- C10: Corresponds to todo-6c (Provide DNS Access) ---
  {
    id: "todo-c10",
    title: "Provide DNS Access for Domain Configuration",
    description:
      "DNS access provided for domain configuration. Website hosting and email routing configured.",
    archetype: "integration",
    status: "completed",
    priority: "medium",
    priorityScore: 0.52,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-01-28T00:00:00Z",
    requestedDate: "2026-01-20T11:00:00Z",
    completedDate: "2026-01-22T16:30:00Z",
    productName: "Website",
    completedData: {
      "Domain Registrar": "Namecheap",
      "Username": "john@bayareaplumbingpros.com",
      "Password": "********** (encrypted)",
      "DNS Status": "Records updated successfully",
    },
  },

  // --- C11: Corresponds to todo-6d (Verify Domain Ownership) ---
  {
    id: "todo-c11",
    title: "Verify Domain Ownership",
    description:
      "Domain ownership verified via TXT record. Website setup can proceed.",
    archetype: "integration",
    status: "completed",
    priority: "medium",
    priorityScore: 0.50,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-01-29T00:00:00Z",
    requestedDate: "2026-01-20T12:00:00Z",
    completedDate: "2026-01-23T11:00:00Z",
    productName: "Website",
    completedData: {
      "Domain": "bayareaplumbingpros.com",
      "Verification Method": "DNS TXT Record",
      "Status": "Verified",
    },
  },

  // --- C12: Corresponds to todo-7 (Provide SEO Keywords) ---
  {
    id: "todo-c12",
    title: "Provide SEO Keywords",
    description:
      "SEO target keywords and location submitted for campaign setup.",
    archetype: "information_request",
    status: "completed",
    priority: "medium",
    priorityScore: 0.48,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-01-29T00:00:00Z",
    requestedDate: "2026-01-19T09:00:00Z",
    completedDate: "2026-01-21T15:30:00Z",
    productName: "Local SEO",
    completedData: {
      "Target Keywords": "plumber near me, emergency plumbing, drain cleaning, water heater repair, pipe leak fix",
      "Target Location": "San Francisco, CA",
    },
  },

  // --- C13: Corresponds to todo-7b (Provide Website Login Credentials) ---
  {
    id: "todo-c13",
    title: "Provide Website Login Credentials",
    description:
      "Website admin credentials submitted for technical SEO and content updates.",
    archetype: "information_request",
    status: "completed",
    priority: "medium",
    priorityScore: 0.46,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 3,
    dueDate: "2026-01-27T00:00:00Z",
    requestedDate: "2026-01-20T09:30:00Z",
    completedDate: "2026-01-20T14:00:00Z",
    productName: "Website Design",
    completedData: {
      "Admin URL": "https://bayareaplumbingpros.com/wp-admin",
      "Username": "admin_john",
      "Password": "********** (encrypted)",
      "CMS": "WordPress 6.4",
    },
  },

  // --- C14: Corresponds to todo-7c (Upload Required Documents) ---
  {
    id: "todo-c14",
    title: "Upload Required Documents",
    description:
      "Business license, insurance certificate, and supporting documents uploaded.",
    archetype: "information_request",
    status: "completed",
    priority: "low",
    priorityScore: 0.42,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-01-31T00:00:00Z",
    requestedDate: "2026-01-20T10:00:00Z",
    completedDate: "2026-01-24T11:00:00Z",
    productName: "Account Setup",
    completedData: {
      "Business License": "license-2026.pdf",
      "Insurance Certificate": "insurance-cert-2026.pdf",
      "Additional Documents": "contractor-certification.pdf",
    },
  },

  // --- C15: Corresponds to todo-7d (Submit Review Replies) ---
  {
    id: "todo-c15",
    title: "Submit Review Replies",
    description:
      "Replies for recent customer reviews drafted and submitted.",
    archetype: "information_request",
    status: "completed",
    priority: "low",
    priorityScore: 0.38,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 15,
    dueDate: "2026-02-02T00:00:00Z",
    requestedDate: "2026-01-22T08:00:00Z",
    completedDate: "2026-01-25T16:00:00Z",
    productName: "Reputation Management",
    completedData: {
      "Reviews Replied": "4 reviews",
      "Platforms": "Google (3), Yelp (1)",
      "Sample Reply": "Thank you for your kind words! We're glad we could help with your plumbing emergency...",
    },
  },

  // --- C16: Corresponds to todo-10 (Provide Additional Info for Vendor) ---
  {
    id: "todo-c16",
    title: "Provide Additional Information Requested by Vendor",
    description:
      "Services list, service areas, and testimonials provided to the vendor for website content.",
    archetype: "vendor_request",
    status: "completed",
    priority: "high",
    priorityScore: 0.72,
    blocking: false,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 10,
    dueDate: "2026-01-25T00:00:00Z",
    requestedDate: "2026-01-22T10:00:00Z",
    completedDate: "2026-01-23T14:30:00Z",
    productName: "Website Design",
    vendorMessage:
      "Hi! We need a few more details to finalize the service pages.",
    completedData: {
      "Services Offered": "Residential Plumbing, Commercial Plumbing, Drain Cleaning, Water Heater, Pipe Repair",
      "Service Areas": "San Francisco, Oakland, Berkeley, Daly City, South San Francisco",
      "Testimonials": "3 customer testimonials provided",
    },
  },

  // --- C17: Corresponds to todo-10b (Website Draft Ready for Review) ---
  {
    id: "todo-c17",
    title: "Website Draft Ready for Review",
    description:
      "Website design draft reviewed and feedback submitted to vendor.",
    archetype: "vendor_request",
    status: "completed",
    priority: "high",
    priorityScore: 0.70,
    blocking: false,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 20,
    dueDate: "2026-01-26T00:00:00Z",
    requestedDate: "2026-01-23T11:00:00Z",
    completedDate: "2026-01-25T10:00:00Z",
    productName: "Website Design",
    vendorMessage:
      "The website design is complete and ready for your review.",
    vendorFiles: ["website-design-preview-v2.pdf", "mobile-mockups.pdf"],
    completedData: {
      "Decision": "Approved with changes",
      "Feedback": "Update hero image, adjust CTA button color to brand blue. Rest looks good.",
      "Pages Reviewed": "Homepage, About, Services (5 pages), Contact",
    },
  },

  // --- C18: Corresponds to todo-10c (Ads Campaign - Approval Required) ---
  {
    id: "todo-c18",
    title: "Ads Campaign Created - Approval Required",
    description:
      "Google Ads campaign reviewed and approved for launch.",
    archetype: "vendor_request",
    status: "completed",
    priority: "medium",
    priorityScore: 0.60,
    blocking: false,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 10,
    dueDate: "2026-01-28T00:00:00Z",
    requestedDate: "2026-01-24T09:00:00Z",
    completedDate: "2026-01-26T11:00:00Z",
    productName: "PPC Management",
    vendorMessage:
      "Your Google Ads campaign is ready! 3 ad groups, 25 keywords, $50/day budget.",
    vendorFiles: ["campaign-setup-summary.pdf"],
    completedData: {
      "Decision": "Approved",
      "Daily Budget": "$50",
      "Keywords Approved": "25",
      "Campaign Launched": "Jan 28, 2026",
    },
  },

  // --- C19: Corresponds to todo-10d (SSL Activation Pending) ---
  {
    id: "todo-c19",
    title: "SSL Activation Pending",
    description:
      "Domain ownership confirmed and SSL certificate activated.",
    archetype: "vendor_request",
    status: "completed",
    priority: "medium",
    priorityScore: 0.56,
    blocking: false,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 5,
    dueDate: "2026-01-29T00:00:00Z",
    requestedDate: "2026-01-23T14:00:00Z",
    completedDate: "2026-01-24T09:30:00Z",
    productName: "Website",
    vendorMessage:
      "We need to activate the SSL certificate for your domain.",
    completedData: {
      "Domain": "bayareaplumbingpros.com",
      "SSL Provider": "Let's Encrypt",
      "Certificate Status": "Active",
      "Expires": "Apr 24, 2026",
    },
  },

  // --- C20: Corresponds to todo-11 (Pay / Approve Invoice) ---
  {
    id: "todo-c20",
    title: "Pay / Approve Invoice",
    description:
      "Invoice reviewed and payment processed successfully.",
    archetype: "payment",
    status: "completed",
    priority: "high",
    priorityScore: 0.80,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-01-22T00:00:00Z",
    requestedDate: "2026-01-19T08:00:00Z",
    completedDate: "2026-01-19T09:15:00Z",
    productName: "Account Billing",
    completedData: {
      "Invoice #": "INV-2026-001",
      "Amount": "$2,500.00",
      "Payment Method": "Visa ending in 4242",
      "Transaction ID": "txn_3PkR9sLq2mN",
    },
  },

  // --- C21: Corresponds to todo-11b (Subscription Payment Failed) ---
  {
    id: "todo-c21",
    title: "Subscription Payment Failed",
    description:
      "Payment method updated and subscription payment retried successfully.",
    archetype: "payment",
    status: "completed",
    priority: "critical",
    priorityScore: 0.93,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-01-20T00:00:00Z",
    requestedDate: "2026-01-17T12:00:00Z",
    completedDate: "2026-01-17T14:30:00Z",
    productName: "Account Billing",
    completedData: {
      "Issue": "Card declined - insufficient funds",
      "Resolution": "Updated to new Mastercard ending in 8811",
      "Retry Status": "Payment successful",
      "Amount Charged": "$499.00",
    },
  },

  // --- C22: Corresponds to todo-11c (Credit Card Expiring Soon) ---
  {
    id: "todo-c22",
    title: "Credit Card Expiring Soon",
    description:
      "Payment card updated before expiration to prevent payment failures.",
    archetype: "payment",
    status: "completed",
    priority: "medium",
    priorityScore: 0.45,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-01-15T00:00:00Z",
    requestedDate: "2026-01-05T10:00:00Z",
    completedDate: "2026-01-08T11:00:00Z",
    productName: "Account Billing",
    completedData: {
      "Old Card": "Visa ending in 1234 (exp. 01/26)",
      "New Card": "Visa ending in 4242 (exp. 09/28)",
      "Updated By": "John Doe",
    },
  },

  // --- C23: Corresponds to todo-11d (Add Payment Method) ---
  {
    id: "todo-c23",
    title: "Add Payment Method",
    description:
      "Payment method added to the account. Plan activation proceeding.",
    archetype: "payment",
    status: "completed",
    priority: "high",
    priorityScore: 0.82,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-01-21T00:00:00Z",
    requestedDate: "2026-01-16T08:00:00Z",
    completedDate: "2026-01-16T08:45:00Z",
    productName: "Account Billing",
    completedData: {
      "Card Type": "Visa",
      "Card Ending": "4242",
      "Expiry": "09/28",
      "Cardholder": "John Doe",
      "Billing Address": "1234 Market Street, San Francisco, CA 94103",
    },
  },

  // --- C24: Corresponds to todo-8 (DNS Misconfiguration Detected) ---
  {
    id: "todo-c24",
    title: "DNS Misconfiguration Detected",
    description:
      "DNS misconfiguration resolved. Website and email delivery functioning normally.",
    archetype: "system_alert",
    status: "completed",
    priority: "high",
    priorityScore: 0.68,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 10,
    dueDate: null,
    requestedDate: "2026-01-19T07:00:00Z",
    completedDate: "2026-01-20T09:00:00Z",
    productName: "Website",
    completedData: {
      "Issue": "MX records misconfigured, A record pointing to old IP",
      "Resolution": "Updated MX records and A record to correct values",
      "Verified By": "System auto-check",
    },
  },

  // --- C25: Corresponds to todo-8b (OAuth Token Expired) ---
  {
    id: "todo-c25",
    title: "OAuth Token Expired",
    description:
      "Google Ads OAuth token re-authorized successfully.",
    archetype: "system_alert",
    status: "completed",
    priority: "high",
    priorityScore: 0.66,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: null,
    requestedDate: "2026-01-20T06:00:00Z",
    completedDate: "2026-01-20T10:30:00Z",
    productName: "PPC Management",
    completedData: {
      "Service": "Google Ads",
      "Account": "john@bayareaplumbingpros.com",
      "Re-authorized On": "Jan 20, 2026 at 10:30 AM",
      "Status": "Token active",
    },
  },

  // --- C26: Corresponds to todo-8c (Tracking Pixel Not Firing) ---
  {
    id: "todo-c26",
    title: "Tracking Pixel Not Firing",
    description:
      "Tracking pixel issue resolved. Conversion tracking now functioning correctly.",
    archetype: "system_alert",
    status: "completed",
    priority: "medium",
    priorityScore: 0.54,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 10,
    dueDate: null,
    requestedDate: "2026-01-20T08:00:00Z",
    completedDate: "2026-01-21T15:00:00Z",
    productName: "PPC Management",
    completedData: {
      "Issue": "Pixel code missing from checkout confirmation page",
      "Resolution": "Pixel reinstalled on all conversion pages",
      "Pages Fixed": "Contact form thank-you, Quote request confirmation",
      "Verified": "Test conversions firing correctly",
    },
  },

  // --- C27: Corresponds to todo-8d (Google Ads Disapproved Ads) ---
  {
    id: "todo-c27",
    title: "Google Ads Disapproved Ads",
    description:
      "Disapproved ads updated and resubmitted. All ads now approved by Google.",
    archetype: "system_alert",
    status: "completed",
    priority: "medium",
    priorityScore: 0.50,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 15,
    dueDate: null,
    requestedDate: "2026-01-21T07:00:00Z",
    completedDate: "2026-01-23T11:30:00Z",
    productName: "PPC Management",
    completedData: {
      "Ads Flagged": "3 ads disapproved",
      "Reason": "Misleading claim in ad copy, trademark issue",
      "Resolution": "Ad copy rewritten, trademark terms removed",
      "Status": "All 3 ads re-approved",
    },
  },

  // --- C28: Corresponds to todo-9 (Select Business Category) ---
  {
    id: "todo-c28",
    title: "Select Business Category",
    description:
      "Business category selected for local search engine optimization.",
    archetype: "information_request",
    status: "completed",
    priority: "low",
    priorityScore: 0.30,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 3,
    dueDate: "2026-02-02T00:00:00Z",
    requestedDate: "2026-01-19T10:00:00Z",
    completedDate: "2026-01-19T10:15:00Z",
    productName: "Local SEO",
    completedData: {
      "Business Category": "Plumbing",
      "Secondary Categories": "Emergency Plumber, Water Heater Installation",
    },
  },

  // --- C29: Corresponds to todo-9b (Provide PPC Keywords) ---
  {
    id: "todo-c29",
    title: "Provide PPC Keywords",
    description:
      "PPC target keywords submitted for Google Ads campaign setup.",
    archetype: "information_request",
    status: "completed",
    priority: "low",
    priorityScore: 0.28,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-02-02T00:00:00Z",
    requestedDate: "2026-01-20T10:30:00Z",
    completedDate: "2026-01-22T09:00:00Z",
    productName: "PPC Management",
    completedData: {
      "PPC Keywords": "emergency plumber, water heater repair, pipe leak fix, drain cleaning near me, 24/7 plumber SF",
      "Negative Keywords": "DIY plumbing, plumbing school, plumbing jobs",
    },
  },
]
