import type { Todo } from "./todo-types"

export const mockTodos: Todo[] = [
  // === OPEN TODOS (sorted by priorityScore desc) ===
  {
    id: "todo-1",
    title: "Update Payment Method",
    description:
      "Your credit card on file has expired. Please update your payment method to avoid any disruption to your active campaigns.",
    archetype: "payment",
    status: "not_started",
    priority: "critical",
    priorityScore: 0.92,
    blocking: true,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 3,
    dueDate: "2026-02-08T00:00:00Z",
    requestedDate: "2026-02-04T10:00:00Z",
    productName: "Account Billing",
    fields: [
      {
        id: "card_number",
        label: "Card Number",
        type: "text",
        placeholder: "1234 5678 9012 3456",
        helpText: "Enter your 16-digit card number",
        required: true,
      },
      {
        id: "expiry",
        label: "Expiry Date",
        type: "text",
        placeholder: "MM/YY",
        helpText: "Enter the expiration date on your card",
        required: true,
      },
      {
        id: "cvv",
        label: "CVV",
        type: "text",
        placeholder: "123",
        helpText: "3-digit security code on the back of your card",
        required: true,
      },
    ],
  },
  {
    id: "todo-2",
    title: "Connect Google Business Profile",
    description:
      "Connect your Google Business Profile so we can manage your local listing, respond to reviews, and track local search performance.",
    archetype: "integration",
    status: "not_started",
    priority: "high",
    priorityScore: 0.85,
    blocking: true,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-02-10T00:00:00Z",
    requestedDate: "2026-02-03T14:30:00Z",
    productName: "Local SEO",
    fields: [
      {
        id: "gbp_action",
        label: "Connection Method",
        type: "dropdown",
        helpText: "Choose how you'd like to connect your Google Business Profile",
        required: true,
        options: ["Connect existing GBP", "Create new GBP for me"],
      },
    ],
  },
  {
    id: "todo-3",
    title: "Upload Business Logo",
    description:
      "Upload a high-resolution version of your business logo. This will be used across your website, social media profiles, and marketing materials.",
    archetype: "information_request",
    status: "in_progress",
    priority: "high",
    priorityScore: 0.78,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-02-12T00:00:00Z",
    requestedDate: "2026-02-02T09:00:00Z",
    productName: "Website Design",
    fields: [
      {
        id: "logo_file",
        label: "Logo File",
        type: "file",
        helpText:
          "Upload PNG, SVG, or AI format. Minimum 500x500px recommended.",
        required: true,
      },
      {
        id: "logo_guidelines",
        label: "Brand Guidelines (Optional)",
        type: "file",
        helpText: "Upload any brand guidelines document if available",
        required: false,
      },
    ],
  },
  {
    id: "todo-4",
    title: "Approve Website Draft",
    description:
      "Your website draft is ready for review. Please review all pages and approve or request changes.",
    archetype: "feedback_request",
    status: "not_started",
    priority: "high",
    priorityScore: 0.74,
    blocking: true,
    targetActor: "business",
    sourceActor: "vendor",
    estimatedMinutes: 15,
    dueDate: "2026-02-11T00:00:00Z",
    requestedDate: "2026-02-05T11:00:00Z",
    productName: "Website Design",
    vendorMessage:
      "Hi! We have completed the initial draft of your website. Please review the homepage, about page, and service pages. Let us know if you'd like any changes to the layout, colors, or content.",
    vendorFiles: ["website-draft-preview.pdf"],
  },
  {
    id: "todo-5",
    title: "Provide Hosting Credentials",
    description:
      "We need access to your current hosting provider to migrate your website. Please provide your hosting login credentials securely.",
    archetype: "information_request",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.62,
    blocking: true,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-02-14T00:00:00Z",
    requestedDate: "2026-02-04T08:00:00Z",
    productName: "Website Migration",
    fields: [
      {
        id: "host_provider",
        label: "Hosting Provider",
        type: "text",
        placeholder: "e.g., GoDaddy, Bluehost, SiteGround",
        helpText: "Name of your current hosting provider",
        required: true,
      },
      {
        id: "host_username",
        label: "Username / Email",
        type: "email",
        placeholder: "your-email@example.com",
        required: true,
      },
      {
        id: "host_password",
        label: "Password",
        type: "credentials",
        helpText:
          "Your credentials are encrypted and stored securely. They will only be used for migration.",
        required: true,
      },
    ],
  },
  {
    id: "todo-6",
    title: "Connect Google Ads Account",
    description:
      "Connect your Google Ads account to enable campaign management and performance tracking.",
    archetype: "integration",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.55,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 5,
    dueDate: "2026-02-15T00:00:00Z",
    requestedDate: "2026-02-03T16:00:00Z",
    productName: "PPC Management",
    fields: [
      {
        id: "gads_action",
        label: "Connection Method",
        type: "dropdown",
        helpText: "Choose how you'd like to connect Google Ads",
        required: true,
        options: [
          "Connect existing Google Ads",
          "Set up a new Google Ads account for me",
        ],
      },
    ],
  },
  {
    id: "todo-7",
    title: "Provide SEO Keywords",
    description:
      "Share the keywords you'd like to target for your SEO campaign. If you're unsure, we'll suggest keywords based on your industry and location.",
    archetype: "information_request",
    status: "not_started",
    priority: "medium",
    priorityScore: 0.48,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-02-16T00:00:00Z",
    requestedDate: "2026-02-03T09:00:00Z",
    productName: "Local SEO",
    fields: [
      {
        id: "keywords",
        label: "Target Keywords",
        type: "textarea",
        placeholder:
          "e.g., plumber near me, emergency plumbing, drain cleaning",
        helpText:
          "Enter keywords separated by commas. We recommend 5-10 primary keywords.",
        required: true,
      },
      {
        id: "location",
        label: "Target Location",
        type: "text",
        placeholder: "e.g., San Francisco, CA",
        helpText: "Primary service area for your SEO campaign",
        required: true,
      },
    ],
  },
  {
    id: "todo-8",
    title: "DNS Configuration Alert",
    description:
      "We detected a DNS misconfiguration on your domain. This may affect your website performance and email delivery.",
    archetype: "system_alert",
    status: "not_started",
    priority: "low",
    priorityScore: 0.35,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 10,
    dueDate: null,
    requestedDate: "2026-02-05T07:00:00Z",
    productName: "Website",
  },
  {
    id: "todo-9",
    title: "Select Business Category",
    description:
      "Choose the most appropriate business category. This helps search engines understand your business and show it in relevant results.",
    archetype: "information_request",
    status: "not_started",
    priority: "low",
    priorityScore: 0.30,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 3,
    dueDate: "2026-02-20T00:00:00Z",
    requestedDate: "2026-02-03T10:00:00Z",
    productName: "Local SEO",
    fields: [
      {
        id: "category",
        label: "Business Category",
        type: "dropdown",
        helpText: "Select the primary category that best describes your business",
        required: true,
        options: [
          "Plumbing",
          "Electrical",
          "HVAC",
          "Roofing",
          "General Contractor",
          "Landscaping",
          "Cleaning Service",
          "Auto Repair",
          "Dental",
          "Medical Practice",
          "Law Firm",
          "Restaurant",
          "Other",
        ],
      },
    ],
  },

  // === COMPLETED TODOS ===
  {
    id: "todo-c1",
    title: "Provide Business Information",
    description:
      "Business name, address, phone number, and operating hours have been submitted.",
    archetype: "information_request",
    status: "completed",
    priority: "high",
    priorityScore: 0.82,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 10,
    dueDate: "2026-02-05T00:00:00Z",
    requestedDate: "2026-02-01T09:00:00Z",
    completedDate: "2026-02-03T14:22:00Z",
    productName: "Website Design",
  },
  {
    id: "todo-c2",
    title: "Verify Email Address",
    description: "Your email address has been verified successfully.",
    archetype: "system_alert",
    status: "completed",
    priority: "critical",
    priorityScore: 0.95,
    blocking: false,
    targetActor: "business",
    sourceActor: "system",
    estimatedMinutes: 2,
    dueDate: "2026-02-02T00:00:00Z",
    requestedDate: "2026-02-01T08:00:00Z",
    completedDate: "2026-02-01T08:05:00Z",
    productName: "Account Setup",
  },
  {
    id: "todo-c3",
    title: "Confirm Business Address",
    description:
      "Business address confirmed for local listing and map placement.",
    archetype: "feedback_request",
    status: "completed",
    priority: "medium",
    priorityScore: 0.60,
    blocking: false,
    targetActor: "business",
    sourceActor: "plan_executor",
    estimatedMinutes: 3,
    dueDate: "2026-02-06T00:00:00Z",
    requestedDate: "2026-02-02T10:00:00Z",
    completedDate: "2026-02-04T16:45:00Z",
    productName: "Local SEO",
  },
]
